ca/urls.py
from django.conf.urls import patterns, url, include
from haystack.forms import FacetedSearchForm
from haystack.query import SearchQuerySet
from haystack.views import FacetedSearchView
from ca import views

sqs = SearchQuerySet().facet('degree').facet('university').facet('major').facet('academic_professional')

urlpatterns = patterns('',
        url(r'^$', views.home, name = 'home'),
        url(r'^articles/$', views.articles, name = 'articles'),
        url(r'^article_detail/(?P<article_id>\d+)/$', views.article_detail, name = 'article_detail'),
        url(r'^register/$', views.register, name = 'register'),
        url(r'^login/$', views.user_login, name = 'login'),
        url(r'^logout/$', views.user_logout, name = 'logout'),
        url(r'^profile/$', views.profile, name = 'profile'),
        url(r'^edit_profile/$', views.edit_profile, name = 'edit_profile'),
        url(r'^program_search/', views.search_haystack, name = 'program_search'),
        url(r'^program_detail/(?P<program_id>\d+)/$', views.program_detail, name = 'program_detail'),
        url(r'^add_fav_program', views.add_fav_program, name = 'add_fav_program'),
        url(r'^rm_fav_program', views.rm_fav_program, name = 'rm_fav_program'),
        )
urlpatterns += patterns('haystack.views',
        url(r'^search/$', FacetedSearchView(form_class=FacetedSearchForm, searchqueryset=sqs), name='search'),
        )

caml/urls.py
from django.views.generic import RedirectView
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'caml.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', RedirectView.as_view(url='/ca/')), 
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ca/', include('ca.urls', namespace = 'ca')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ca/forms.py
from django import forms
from ca.models import UserProfile, Program, University, Package
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

# Minimum length of password required
MINIMUM_PASSWORD_LENGTH = 6

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput)
    password_confirmation = forms.CharField(widget = forms.PasswordInput)
    username = forms.CharField()
    email = forms.CharField()

    # Set required minimum password length
    def clean_password(self):
        pw = self.cleaned_data.get('password')
        if len(pw) < MINIMUM_PASSWORD_LENGTH:
            raise ValidationError('Password cannot be shorter than 6 letters.')
        return pw

    def clean_password_con(self):
        pw1 = self.cleaned_data.get('password')
        pw2 = self.cleaned_data.get('password_confirmation')
        if pw1 and pw1 != pw2:
            raise forms.ValidationError("Passwords don't match")
        return pw2

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    # year_status = forms.ModelChoiceField(queryset = UserProfile.YEAR_STATUS_CHOICES, required = True)
    picture = forms.ImageField(help_text = "Select an image", required = False)
    fav_program = forms.ModelMultipleChoiceField(queryset = Program.objects.all(), to_field_name = "name", required = False)
    fav_university = forms.ModelMultipleChoiceField(queryset = University.objects.all(), required = False)
    packages = forms.ModelMultipleChoiceField(queryset = Package.objects.all(), required = False)
    class Meta:
        model = UserProfile
        fields = ['about_me', 'year_status', 'phone', 'picture', 'skype_id', 'qq_id', 'fav_program', 'fav_university', 'packages']

class UserRegisterForm(forms.ModelForm):
    # year_status = forms.ModelChoiceField(queryset = UserProfile.YEAR_STATUS_CHOICES, required = True)
    class Meta:
        model = UserProfile
        fields = ['year_status']

class EditUserForm(forms.ModelForm):
    password = forms.CharField(help_text = "Password")
    username = forms.CharField(help_text = "Username")
    email = forms.CharField(help_text = "Email")
    class Meta:
        model = User
        fields = ['username', 'password', 'email']

class EditProfileForm(forms.ModelForm):
    username = forms.CharField(required = True)
    email = forms.EmailField(required = True)
    class Meta:
        model = UserProfile
        fields = ['phone', 'picture', 'skype_id', 'qq_id']

class ProgramDetailForm(forms.ModelForm):
    class Meta:
        model = Program
        exclude = ['university', 'program_category', 'name', 'career', 'faculty', 'attendance rate', 'percentage_chinese', 'undergrad_institution']

ca/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.template import RequestContext
from django.core.urlresolvers import reverse
from ca.models import UserProfile, Program, Package, Tracking, Article, University
from ca.forms import UserProfileForm, UserForm, UserRegisterForm, ProgramDetailForm
from django.views import generic
from haystack.query import SearchQuerySet
from haystack.views import FacetedSearchView
from haystack.forms import FacetedSearchForm
import simplejson as json

# Global constant
MAX_PROGRAM = 10 # Max number of programs that can be shown in the result list

def home(request):
    context = RequestContext(request)
    return render_to_response('ca/home.html', context)


def register(request):
    context = RequestContext(request)
    registered = False
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserRegisterForm(request.POST, request.FILES)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit = False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
                print "Profile photo uploaded."

            profile.save()

            # ManyToMany relationships can't be added until after the model object is saved
            """
            selected_fav_programs = profile_form.cleaned_data['fav_program']
            if selected_fav_programs:
                profile.fav_program = selected_fav_programs
            selected_packages = profile_form.cleaned_data['packages']
            if selected_packages:
                for package in selected_packages:
                    tracking = Tracking.objects.get_or_create(package = package, user = profile)
                    print tracking
                    tracking[0].save()
            """
            profile.save()
            registered = True
            # Deal with the favorite programs

    else:
        user_form = UserForm()
        profile_form = UserRegisterForm()
    return render_to_response('ca/register.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        'registered': registered,
        }, context)

def user_login(request):
    context = RequestContext(request)
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username = username, password = password)
        if user is not None:
            if user.is_active:
                user.backend = 'django.contrib.auth.backends.ModelBackend'
                login(request, user)
                return HttpResponseRedirect('/ca/')
            else:
                return HttpResponse('Your account has been disabled')
        else:
            print "Invalid login details: {0}, {1}".format(username, password)
            return render_to_response("ca/login.html", {'bad_details': True}, context)
    else:
        return render_to_response('ca/login.html', {'bad_details': False}, context)

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/ca/')

@login_required
def profile(request):
    context = RequestContext(request)
    user = request.user
    profile = UserProfile.objects.get(user = user)
    return render_to_response('ca/profile.html', {'profile': profile, 'user': user}, context)

@login_required
def edit_profile(request):
    context = RequestContext(request)
    user = request.user
    if user.is_authenticated():
        profile = UserProfile.objects.get(user = user)

        if request.method == "POST":

            print request.FILES
            update_user_form = UserForm(request.POST, instance = user)
            update_profile_form = UserProfileForm(request.POST, request.FILES, instance = profile)
            if update_user_form.is_valid():
                if update_profile_form.is_valid():
                    user = update_user_form.save()
                    user.set_password(user.password)
                    profile = update_profile_form.save(commit = False)
                    selected_fav_programs = update_profile_form.cleaned_data['fav_program']
                    selected_packages = update_profile_form.cleaned_data['packages']
                    # TODO: remove tracking for not_selected_packages
                    # TODO: highlight packages, fav_programs that are already selected before
                    profile.fav_program = selected_fav_programs
                    if 'picture' in request.FILES:
                        profile.picture = request.FILES['picture']
                        print "Profile photo updated."

                    # Manually save M2M through relationship
                    for package in selected_packages:
                        tracking = Tracking.objects.get_or_create(package = package, user = profile)
                        print tracking
                        tracking[0].save()
                    user.save()
                    profile.save()
                    print "Update profile successful"
                    # Redirect to profile page
                    return render_to_response("ca/profile.html", {
                        'user': user,
                        'profile': profile,
                        }, context)
        else:
            update_user_form = UserForm(instance = user)
            update_profile_form = UserProfileForm(instance = profile, initial = {'packages': [p.id for p in profile.packages.all()]})

        return render_to_response('ca/edit_profile.html', {
                    'profile': profile,
                    'user': user,
                    'edituser': update_user_form,
                    'editprofile': update_profile_form,
                    },
                context)
    else:
        # TODO: Your session has timed out!
        pass 

# Helper function for program_search()
# TODO: delete duplicate search, add second category
def search_program(starts_with = {}):
    program_list = []
    if starts_with:
        filterargs = {}
        for k, v in starts_with.iteritems():
            if v:
                # Ignore case
                filterargs['{0}__{1}'.format(k, 'icontains')] = v

        if filterargs:
            program_list = Program.objects.filter(**filterargs)
        else:
            program_list = Program.objects.all()
    else:
        program_list = Program.objects.all()

    return program_list

def program_search(request):
    context = RequestContext(request)
    starts_with = {}
    programs_list = []

    field_list = ['name']
    if request.method == "GET":
        for field in field_list:
            starts_with[field] = request.GET['search_' + field]
    else:
        for field in field_list:
            starts_with[field] = request.POST['search_' + field]

    program_list = search_program(starts_with)
    # Limit the number of program to be rendered to HTML
    if MAX_PROGRAM > 0:
        if len(program_list) > MAX_PROGRAM:
            limit_program_list = program_list[:MAX_PROGRAM]
        else:
            limit_program_list = program_list

    # Save the whole resulted program_list to session, to be used by categories for subsetting
    # First convert to JSON object

    # Get the categories
    # max number of sub-categories that can be shown
    max_counts = 6
    top_counts = []

    return render_to_response('ca/program_search.html', {'program_list': limit_program_list}, context)

@login_required
def program_detail(request, program_id):
    context = RequestContext(request)
    if program_id:
        program = Program.objects.get(pk = program_id)
        program_fields = program._meta.get_all_field_names()
        fields = [x for x in program_fields if x not in ['id', 'userprofile', 'university', 'program_category', 'name', 'career', 'faculty', 'attendance rate', 'percentage_chinese', 'undergrad_institution']]
        values = [getattr(program, x) for x in fields]
        # Change the font, stylish
        fields = [x.title() for x in fields]
        fields = [x.replace("_", " ") for x in fields]

        final_dict = dict(zip(fields, values))

        # Find the corresponding university
        univ = University.objects.filter(name__exact = program.university)
        univ_obj = univ[0]
    else:
        program = None
        final_dict = None
        univ_obj = None
    return render_to_response('ca/program_detail.html', {
        'program': program,
        'field_dict': final_dict, 
        'univ': univ_obj,
        }, context)

# Simple view of one article
def articles(request):
    context = RequestContext(request)
    return render_to_response('ca/articles.html', {
        'articles': Article.objects.all(),
        }, context)

def article_detail(request, article_id):
    context = RequestContext(request)
    if article_id: 
        article = Article.objects.get(pk = article_id)
        article_title = article.title
        article_body = article.body
    return render_to_response('ca/article_detail.html', {
        'article_title': article_title,
        'article_body': article_body,
        }, context)

def search_haystack(request):
    if request.method == "GET" and request.GET['search_name']:
        program = SearchQuerySet().autocomplete(content_auto=request.GET.get('search_name',''))[:5]
        # program is of SearchResult class, need to call .object to retrieve its field
        suggestions = [p.object for p in program]
    else: 
        suggestions = None
    # Make sure return a JSON object, not a bare list
    # Otherwise would be vulnerable to an XSS attack.
    """
    suggestions_json = json.dumps({

ca/templates/ca/article_detail.html
{% extends 'ca/base.html' %}
{% load static %}
{% block body %}
{% if article_title %}
<label>{{ article_title }}</label>
<p>{{ article_body|safe }}</p>
{% endif %}
{% endblock %}

ca/templates/ca/articles.html
{% extends 'ca/base.html' %}
{% load static %}
{% block body %}
{% if articles %}
    <legend>List of articles</legend>
    <ul>
    {% for article in articles %}
    <li><a href="{% url 'ca:article_detail' article.id %}">{{ article.title }}</a></li>   
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

ca/templates/ca/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
        {% block head %}{% endblock %}
        <link href="{% static 'css/base.css' %}" rel="stylesheet">
        <link href="{% static 'css/program_search.css' %}" rel="stylesheet">
        <script type="text/javascript" src="{% static 'js/jquery-2.0.3.min.js' %}"></script>
        <title>CAML! - {% block title%}Way to Education!{% endblock %}</title>
    </head>
    <body>
        <div class="wrapper">
        <div class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'ca:home' %}">CAML</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a  href="{% url 'ca:articles' %}">Articles</a></li>
                        <li><a href="{% url 'ca:search' %}">Search</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'ca:profile' %}">{{ user.username }}</a></li>
                        <li><a href="{% url 'ca:logout' %}">Logout</a></li>
                        {% else %}
                        <li><a href="{% url 'ca:register'  %}">Register</a></li>
                        <li><a href="{% url 'ca:login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>

        <div class="container" id="body_block"  role="main">
            {% block body %}{% endblock %}
        </div>
        <div class="push"></div>
    </div>
        <div class="footer">
            <div class="container">
                <p class="text-muted">&copy; CAML: Get In, Fit in, Stand out. </p>
            </div>
        </div>
        <script type="text/javascript" src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/program_search.js' %}"></script>
    </body>
</html>

ca/templates/ca/base_bk.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta name="viewpoint" content="width=device-with, initial-scale=1.0">
        <link href="{% static 'css/bootstrap-fluid-adj.css' %}" rel="stylesheet">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
        <link href="{% static 'css/bootstrap-responsive.css' %}" rel="stylesheet">
        <link href="{% static 'css/base.css' %}" rel="stylesheet">
       <link href="{% static 'css/program_search.css' %}" rel="stylesheet">
        <script type="text/javascript" src="{% static 'js/jquery-2.0.3.min.js' %}"></script>
        <title>CAML! - {% block title%}Way to Education!{% endblock %}</title>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="brand" href="{% url 'ca:home' %}">CAML</a>
                    <div class="nav-collapse collapse">
                        <ul class="nav pull-left">
                            <li><a  href="{% url 'ca:articles' %}">Articles</a></li>
                            <li><a href="{% url 'ca:search' %}">Search</a></li>
                        </ul>
                    </div>
                    <div class="nav-collapse collapse">
                        <ul class="nav pull-right">
                            {% if user.is_authenticated %}
                            <li><a href="{% url 'ca:profile' %}">{{ user.username }}</a></li>
                            <li><a href="{% url 'ca:logout' %}">Logout</a></li>
                            {% else %}
                            <li><a href="{% url 'ca:register'  %}">Register</a></li>
                            <li><a href="{% url 'ca:login' %}">Login</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="container-fluid">
            <div class="row-fluid">
                <div class="span12">
                    {% block body %}{% endblock %}
                </div>
            </div>
        </div>

        <hr/>
        <footer>
        <div class="container">
            <p>&copy; CAML: Your Way to Education.</p>
        </div>
        </footer>
        <script type="text/javascript" src="{% static 'js/jquery-2.0.3.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/program_search.js' %}"></script>
    </body>
</html>

ca/templates/ca/edit_profile.html
{% extends 'ca/base.html' %}
{% load static %}
{% load bootstrap %}
{% block head %}
<link href="{% static 'css/profile.css' %}" rel="stylesheet">
{% endblock %}
{% block body %}
<h2>Edit Profile</h2>
<form id="edit_profile_form" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <legend>Required Information</legend>
    {{ edituser|bootstrap }}
    {% if profile %}
    <legend>Additional Information</legend>
    {{ editprofile|bootstrap }}
    {% endif %}
    <button class="btn btn-primary" type="submit">Save Profile</button>
</form>
{% endblock %}

ca/templates/ca/home.html
{% extends 'ca/base.html' %}
{% load static %}
{% block body %}
<div class="hero-unit">
    <img src="{{ MEDIA_URL }}logos/moonlight_long.jpg"/>
</div>
{% endblock %}

ca/templates/ca/invalid_login.html
{% extends 'ca/base.html' %}
{% load static %}
{% block body %}
<strong>Your have entered invalid username/password.</strong>
{% endblock %}

ca/templates/ca/login.html
{% extends 'ca/base.html' %}
{% load static %}
{% block head %}
<link href="{% static 'css/signin.css' %}" rel="stylesheet">
{% endblock %}
{% block title %}Sign in to CAMoonlight{% endblock %}
{% block body %}
    <form class="form-signin " id="login_form" method="post">

        <h2 class="form-signin-heading">Please log in</h2>
        {% csrf_token %}
        {% if bad_details %}
        <p><strong>Your username and/or password were incorrect.</strong></p>
        {% elif disabled_account %}
        <p><strong>Your account has been disabled/</strong></p>
        {% endif %}

        <input type="text" class="form-control" placeholder="Username" name="username" value="" size="50" />
        <input type="password" class="form-control" placeholder="Password" name="password" value="" size="50" />
        <br/>
        <button class="btn btn-primary btn-lg btn-block" type="submit">Login</button>
    </form>
{% endblock %}

ca/templates/ca/profile.html
{% extends 'ca/base.html' %}
{% load static %}
{% block head %}
<link href="{% static 'css/profile.css' %}" rel="stylesheet">
{% endblock %}
{% block title %}Your user profile{% endblock %}
{% block body %}
{% if profile %}
<div class="jumbotron">
    <h1>Hello,&nbsp;{{ user.username }}</h1>
    <br>
    <p>
    <a href="{% url 'ca:edit_profile' %}" class="btn btn-primary btn-lg" role="button">Edit your information</a>
    </p>
</div>
<form class="" method="post" id="profile_form">
    {% csrf_token %}
    <div class="page-header"><h1>Basic Information</h1></div>
    <table class="table borderless">
        <tbody>
            <tr>
                <td>Username:</td>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <td>Current year:</td>
                <td>{{ profile.year_status }}</td>
            </tr>
            <tr>
                <td>Email:</td>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <td>About me:</td>
                <td>
                    {% if profile.about_me %}
                    {{ profile.about_me }}
                    {% endif %}</td>
            </tr>
 
        </tbody>
    </table>

    <div class="page-header"><h1>Additional Information</h1></div>
    <table class="table borderless">
        <tbody>
            <tr>
                <td>Phone number:</td>
                <td>
                    {% if profile.phone %}
                    {{ profile.phone }}
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td>Skype ID:</td>
                <td>{{ profile.skype_id }}</td>
            </tr>
            <tr>
                <td>QQ ID:</td>
                <td>{{ profile.qq_id }}</td>
            </tr>
            <tr>
                <td>Profile photo:</td>
                <td><img src="{{ MEDIA_URL }}{{ profile.picture }}" alt="Image"/></td>
            </tr>
            <tr>
                <td>Package subscription:</td>
                <td>
                    {% if profile.packages %}
                    <ul>
                        {% for package in profile.packages.all %}
                        <li>{{ package.package_name }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td>Favorite program(s):</td>
                <td>
                    {% if profile.fav_program %}
                    <ul>
                        {% for program in profile.fav_program.all %}
                        <li><a href="{% url 'ca:program_detail' program.id %}">{{ program }}</a></li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td>Favorite university(s):</td>
                <td>
                    {% if profile.fav_university %}
                    <ul>
                        {% for univ in profile.fav_university.all %}
                        <li>{{ univ }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}

                </td>
            </tr>

        </tbody>
    </table>
</form>
{% else %}
<h1>Your user profile does not exist!</h1>
{% endif %}
{% endblock %}

ca/templates/ca/program_detail.html
{% extends 'ca/base.html' %}
{% load static %}
{% load bootstrap %}
{% block head %}
<link href="{% static 'css/program_detail.css' %}" rel="stylesheet"/>
{% endblock %}
{% block title %}
View program detail: {{ program.name }}
{% endblock %}
{% block body %}
{% if program %}
<div class="jumbotron">
    <h2>{{ program.name }}, {{ program.university }}</h2>
    <a href="{% url 'ca:search' %}" class="btn btn-lg btn-primary">Back to search</a>
    {% if program in user.get_profile.fav_program.all %}
    <button class="btn btn-lg btn-success fav_program_btn" program-id="{{ program.id }}">Unlike</button>
    {% else %}
    <button class="btn btn-lg btn-success fav_program_btn" program-id="{{ program.id }}">Like</button>
    {% endif %}

</div>
<table class="table table-striped">
    <tbody>
        {% for field, value in field_dict.iteritems %}
        <tr>
            <td colspan="2">{{ field }}</td>
            <td colspan="7">{{ value }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<div class="page-header"><h1>{{ program.university }}</h1></div>
<table class="table table-striped">
    <tbody>
        <tr>
            <td colspan="2">Year of Founded</td>
            <td colspan="7">{{ univ.year_founded }}</td>
        </tr>
        <tr>
            <td colspan="2">Public/Private</td>
            <td colspan="7">{{ univ.public_private }}</td>
        </tr>
        <tr>
            <td colspan="2">Enrollment</td>
            <td colspan="7">{{ univ.enrollment }}</td>
        </tr>
        <tr>
            <td colspan="2">Location</td>
            <td colspan="7">{{ univ.location }}</td>
        </tr>
        <tr>
            <td colspan="2">Setting</td>
            <td colspan="7">{{ univ.setting }}</td>
        </tr>
    </tbody>
</table>
{% endif %}
<div class="jumbotron">
    <a href="{% url 'ca:search' %}" class="btn btn-lg btn-primary">Back to search</a>
    {% if program in user.get_profile.fav_program.all %}
    <button class="btn btn-lg btn-success fav_program_btn" program-id="{{ program.id }}">Unlike</button>
    {% else %}
    <button class="btn btn-lg btn-success fav_program_btn" program-id="{{ program.id }}">Like</button>
    {% endif %}
    {% endblock %}

ca/templates/ca/program_search.html
{% if program_list %}
    {% for program in program_list %}
    <li class="program-search-suggestion"><a href="{% url 'ca:program_detail' program.id %}" program_id="{{ program.id }}"> {{ program }} </a></li>
    {% endfor %}
{% else %}
<strong>No programs match your search criteria.</strong>
{% endif %}

ca/templates/ca/register.html
{% extends 'ca/base.html' %}
{% load static %}
{% load bootstrap %}
{% block head %}
<link href="{% static 'css/signin.css' %}" rel="stylesheet">
{% endblock %}
{% block title %}Account Registration{% endblock %}
{% block body %}
<div class="container">
    {% if registered %}
    <div class="jumbotron">
        <h1>Thank you for registering!</h1>
        <p class="lead">Now you can sign in to your new account!</p>
        <p>
        <a class="btn btn-lg btn-success" href="{% url 'ca:login' %}" role="button">Sign in</a>
        </p>
    </div>
    {% else %}
    <form class="form-signin" id="user_register_form" method="post" enctype="multipart/form-data">
        <h2 class="form-signin-heading">Register with CAML</h2>
        {% csrf_token %}
        {{ user_form|bootstrap }}
        {{ profile_form|bootstrap }}
        <button class="btn btn-primary" type="submit">Register</button>
    </form>
    {% endif %}
</div>
{% endblock %}